# Generated by Django 5.0.6 on 2026-04-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('dispatch', 'Dispatch Issue'), ('offer', 'B2B Offer')], max_length=20)),
                ('entity_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
