# Generated by Django 5.2.4 on 2025-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereceipt',
            name='cottage_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کوتاژ'),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='receipt_type',
            field=models.CharField(choices=[('import_agency', 'کوتاژ\u200cوارداتی/عاملیت توزیع'), ('domestic_purchase', 'خرید داخلی')], default='null', max_length=20, verbose_name='نوع رسید انبار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='temp_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره رسید موقت'),
        ),
    ]
