# Generated by Django 5.2.4 on 2025-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehousereceipt_cottage_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousereceipt',
            name='receipt_type',
            field=models.CharField(choices=[('import_cottage', 'کوتاژ\u200cوارداتی'), ('distribution_agency', 'عاملیت توزیع'), ('domestic_purchase', 'خرید داخلی')], max_length=20, verbose_name='نوع رسید انبار'),
        ),
    ]
