# Generated by Django 5.2.4 on 2025-07-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehousereceipt_receipt_type'),
    ]

    operations = [
    ]
