# Generated by Django 5.2.4 on 2025-07-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20250730_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.CharField(blank=True, help_text='برچسب\u200cها را با کاما جدا کنید', max_length=200, verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن'),
        ),
    ]
