# Generated by Django 4.2.23 on 2025-08-01 08:46

from django.db import migrations, models
import uuid
import jdatetime


def generate_system_ids(apps, schema_editor):
    """Generate unique system IDs for existing receivers"""
    Receiver = apps.get_model('warehouse', 'Receiver')
    
    for receiver in Receiver.objects.all():
        if not receiver.system_id or receiver.system_id == 'REC-DEFAULT':
            jalali_date = jdatetime.datetime.now().strftime('%Y%m%d')
            unique_part = str(uuid.uuid4())[:8].upper()
            receiver.system_id = f"REC-{jalali_date}-{unique_part}"
            receiver.save()


def reverse_generate_system_ids(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_customer_tags_alter_customer_address_and_more'),
    ]

    operations = [
        # First add the field as nullable
        migrations.AddField(
            model_name='receiver',
            name='system_id',
            field=models.CharField(max_length=50, null=True, blank=True, editable=False, verbose_name='شناسه سیستمی'),
        ),
        # Generate unique system IDs for existing records
        migrations.RunPython(generate_system_ids, reverse_generate_system_ids),
        # Now make the field non-nullable and unique
        migrations.AlterField(
            model_name='receiver',
            name='system_id',
            field=models.CharField(max_length=50, unique=True, editable=False, verbose_name='شناسه سیستمی'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='unique_id',
            field=models.CharField(help_text='شناسه از اکسل آدرس‌ها', max_length=50, verbose_name='شناسه یکتا'),
        ),
    ]