export type ExportColumn = {
  key: string
  label: string
}

export const OFFER_EXPORT_COLUMNS: ExportColumn[] = [
  { key: "offer_id", label: "شناسه عرضه" },
  { key: "warehouse_receipt_id", label: "شماره رسید انبار" },
  { key: "offer_weight", label: "وزن عرضه" },
  { key: "unit_price", label: "قیمت واحد" },
  { key: "status", label: "وضعیت" },
  { key: "offer_type", label: "نوع عرضه" },
  { key: "offer_date", label: "تاریخ عرضه" },
  { key: "offer_exp_date", label: "تاریخ انقضای عرضه" },
  { key: "description", label: "توضیحات" },
]

export const DISTRIBUTION_EXPORT_COLUMNS: ExportColumn[] = [
  { key: "transfer_id", label: "شناسه انتقال" },
  { key: "customer_name", label: "نام توزیع کننده" },
  { key: "warehouse_receipt_id", label: "شماره رسید انبار" },
  { key: "sales_proforma_serial", label: "سریال پیش فاکتور فروش" },
  { key: "agency_weight", label: "وزن نمایندگی" },
  { key: "unit_price", label: "قیمت واحد" },
  { key: "agency_date", label: "تاریخ نمایندگی" },
  { key: "description", label: "توضیحات" },
]

export const SALE_EXPORT_COLUMNS: ExportColumn[] = [
  { key: "purchase_id", label: "شناسه خرید" },
  { key: "is_distributor", label: "فروش توزیع کننده" },
  { key: "offer_id", label: "شناسه عرضه" },
  { key: "distribution_id", label: "شناسه توزیع" },
  { key: "product_name", label: "عنوان کالا" },
  { key: "customer_name", label: "نام خریدار" },
  { key: "weight", label: "وزن" },
  { key: "unit_price", label: "قیمت واحد" },
  { key: "total_price", label: "مبلغ کل" },
  { key: "sale_date", label: "تاریخ فروش" },
  { key: "purchase_type", label: "نوع پرداخت" },
  { key: "description", label: "توضیحات" },
  { key: "credit_period_1", label: "بازه پرداخت نسیه 1" },
  { key: "credit_amount_1", label: "مبلغ بازه پرداخت نسیه 1" },
  { key: "credit_period_2", label: "بازه پرداخت نسیه 2" },
  { key: "credit_amount_2", label: "مبلغ بازه پرداخت نسیه 2" },
  { key: "credit_period_3", label: "بازه پرداخت نسیه 3" },
  { key: "credit_amount_3", label: "مبلغ بازه پرداخت نسیه 3" },
]

export const ADDRESS_EXPORT_COLUMNS: ExportColumn[] = [
  { key: "purchase_id", label: "کد" },
  { key: "total_weight_purchased", label: "وزن کل خرید" },
  { key: "purchase_date", label: "تاریخ خرید" },
  { key: "unit_price", label: "قیمت هر واحد" },
  { key: "tracking_number", label: "شماره پیگیری" },
  { key: "province", label: "استان" },
  { key: "city", label: "شهرستان" },
  { key: "payment_amount", label: "مبلغ پرداختی" },
  { key: "customoer_account_number", label: "شماره حساب خریدار" },
  { key: "cottage_code", label: "کد کوتاژ" },
  { key: "product_title", label: "عنوان کالا" },
  { key: "description", label: "توضیحات" },
  { key: "payment_method", label: "شیوه پرداخت" },
  { key: "offer_id", label: "شناسه عرضه" },
  { key: "address_register_date", label: "تاریخ ثبت آدرس" },
  { key: "allocation_id", label: "شناسه تخصیص" },
  { key: "customer_name", label: "نام خریدار" },
  { key: "customer_national_code", label: "شناسه ملی خریدار" },
  { key: "customer_postal_code", label: "کدپستی خریدار" },
  { key: "customer_address", label: "آدرس خریدار" },
  { key: "deposit_id", label: "شناسه واریز" },
  { key: "customer_phone", label: "شماره همراه خریدار" },
  { key: "customer_economic_code", label: "شناسه یکتا خریدار" },
  { key: "customer_type", label: "نوع کاربری خریدار" },
  { key: "receiver_name", label: "نام تحویل گیرنده" },
  { key: "receiver_economic_code", label: "شناسه یکتای تحویل" },
  { key: "single", label: "تک" },
  { key: "double", label: "جفت" },
  { key: "trailer", label: "تریلی" },
  { key: "receiver_address", label: "آدرس تحویل" },
  { key: "receiver_postal_code", label: "کد پستی تحویل" },
  { key: "receiver_phone", label: "شماره هماهنگی تحویل" },
  { key: "receiver_national_id", label: "کد ملی تحویل" },
  { key: "purchase_weight", label: "وزن سفارش" },
  { key: "waybilled_weight", label: "وزن بارنامه شده" },
  { key: "non_waybilled_weight", label: "وزن بارنامه نشده" },
  { key: "agreement_period_1", label: "بازه 1 پرداخت توافقی (روز)" },
  { key: "agreement_amount_1", label: "مبلغ بازه 1 توافقی-ریال" },
  { key: "agreement_period_2", label: "بازه 2 پرداخت توافقی (روز)" },
  { key: "agreement_amount_2", label: "مبلغ بازه 2 توافقی-ریال" },
  { key: "agreement_period_3", label: "بازه 3 پرداخت توافقی (روز)" },
  { key: "agreement_amount_3", label: "مبلغ بازه 3 توافقی-ریال" },
]
