# Generated by Django 5.0.6 on 2025-10-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE warehouse_warehousereceipt DROP COLUMN IF EXISTS age;',
            reverse_sql='ALTER TABLE warehouse_warehousereceipt ADD COLUMN age NUMERIC(20, 0);',
        ),
    ]
