# Generated by Django 5.0.6 on 2025-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryfulfillmentitem",
            old_name="shippment_id",
            new_name="shipment_id",
        ),
        migrations.AlterField(
            model_name="warehousereceipt",
            name="cottage_serial_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="warehousereceipt",
            name="receipt_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
