# Generated by Django 5.0.6 on 2025-10-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_link_existing_sales_to_proformas'),
        ('warehouse', '0002_remove_age_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfulfillment',
            name='sales_proforma',
        ),
        migrations.RemoveField(
            model_name='deliveryfulfillment',
            name='validity_date',
        ),
        migrations.RemoveField(
            model_name='deliveryfulfillment',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='b2b_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.b2baddress'),
        ),
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='warehouse_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehousereceipt'),
        ),
    ]
