# Generated by Django 5.0.6 on 2025-08-10 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse",
            "0002_rename_shippment_id_deliveryfulfillmentitem_shipment_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryfulfillmentitem",
            old_name="shippment_price",
            new_name="shipment_price",
        ),
    ]
