# Generated by Django 5.0.6 on 2025-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse",
            "0003_rename_shippment_price_deliveryfulfillmentitem_shipment_price",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchissueitem",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
