# Generated by Django 5.0.6 on 2025-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_deliveryfulfillment_sales_proforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfulfillmentitem',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
