# Generated by Django 5.0.6 on 2025-10-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0004_alter_deliveryfulfillmentitem_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfulfillmentitem',
            name='shipment_id',
        ),
        migrations.RemoveField(
            model_name='deliveryfulfillmentitem',
            name='shipment_price',
        ),
        migrations.RemoveField(
            model_name='deliveryfulfillmentitem',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='driver_license_plate',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryfulfillmentitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AddField(
            model_name='deliveryfulfillmentitem',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryfulfillmentitem',
            name='fare',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
