# Generated by Django 5.0.6 on 2025-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_link_existing_sales_to_proformas'),
        ('warehouse', '0005_remove_deliveryfulfillmentitem_shipment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.b2bdistribution'),
        ),
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.b2boffer'),
        ),
        migrations.AddField(
            model_name='deliveryfulfillment',
            name='waybill_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
