# Generated by Django 5.0.6 on 2025-10-26 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_deliveryfulfillment_distribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('column_mappings', models.JSONField(help_text='JSON object mapping field keys to Excel column names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='warehouse.shippingcompany')),
            ],
            options={
                'ordering': ['shipping_company', 'name'],
                'unique_together': {('name', 'shipping_company')},
            },
        ),
    ]
