# Generated by Django 5.0.6 on 2025-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_deliverycolumnmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfulfillment',
            name='waybill_serial',
            field=models.CharField(default='', max_length=100),
        ),
    ]
