# Generated by Django 5.0.6 on 2025-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_deliveryfulfillment_waybill_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfulfillment',
            name='waybill_serial',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
