# Generated by Django 5.2.4 on 2025-07-27 14:04

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_id', models.CharField(max_length=50, unique=True, verbose_name='کد گروه در بازارگاه')),
                ('marketplace_name', models.CharField(max_length=200, verbose_name='نام گروه در بازارگاه')),
                ('marketplace_parent_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد گروه والد در بازارگاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('internal_category', models.ForeignKey(blank=True, help_text='گروه کالایی در سیستم داخلی که این گروه بازارگاه به آن مرتبط است', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.productcategory', verbose_name='گروه کالایی داخلی مرتبط')),
            ],
            options={
                'verbose_name': 'گروه کالایی بازارگاه',
                'verbose_name_plural': 'گروه\u200cهای کالایی بازارگاه',
                'db_table': 'marketplace_product_categories',
                'ordering': ['marketplace_name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_id', models.CharField(max_length=100, unique=True, verbose_name='کد کالا در بازارگاه')),
                ('marketplace_name', models.CharField(max_length=300, verbose_name='نام کالا در بازارگاه')),
                ('marketplace_brand', models.CharField(blank=True, max_length=100, verbose_name='برند در بازارگاه')),
                ('marketplace_model', models.CharField(blank=True, max_length=100, verbose_name='مدل در بازارگاه')),
                ('marketplace_unit', models.CharField(blank=True, max_length=50, verbose_name='واحد در بازارگاه')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='مشخصات فنی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('internal_product', models.ForeignKey(blank=True, help_text='کالا در سیستم داخلی که این کالای بازارگاه به آن مرتبط است', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='کالای داخلی مرتبط')),
                ('marketplace_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceproductcategory', verbose_name='گروه کالایی بازارگاه')),
            ],
            options={
                'verbose_name': 'کالای بازارگاه',
                'verbose_name_plural': 'کالاهای بازارگاه',
                'db_table': 'marketplace_products',
                'ordering': ['marketplace_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده'), ('need_review', 'نیاز به بررسی')], default='pending', max_length=20, verbose_name='وضعیت تطبیق')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, help_text='ضریب تبدیل واحد بازارگاه به واحد داخلی (مثلاً اگر در بازارگاه کیلو و در سیستم داخلی تن باشد: 0.001)', max_digits=10, verbose_name='ضریب تبدیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='ایجادکننده')),
                ('confirmed_by', models.CharField(blank=True, max_length=100, verbose_name='تاییدکننده')),
                ('confirmed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('internal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='کالای داخلی')),
                ('marketplace_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceproduct', verbose_name='کالای بازارگاه')),
            ],
            options={
                'verbose_name': 'تطبیق کالا',
                'verbose_name_plural': 'تطبیق\u200cهای کالا',
                'db_table': 'marketplace_product_mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceproduct',
            index=models.Index(fields=['marketplace_id'], name='marketplace_marketp_dac94b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproduct',
            index=models.Index(fields=['marketplace_name'], name='marketplace_marketp_f43e24_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproduct',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_105acb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together={('marketplace_product', 'internal_product')},
        ),
    ]
