# Generated by Django 5.2.4 on 2025-07-27 15:02

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('warehouse', '0003_alter_warehousereceipt_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه عرضه')),
                ('offer_date', django_jalali.db.models.jDateField(verbose_name='تاریخ عرضه')),
                ('offer_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن عرضه (تن)')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت فروش (ریال)')),
                ('total_price', models.DecimalField(decimal_places=0, editable=False, max_digits=18, verbose_name='مبلغ کل')),
                ('offer_type', models.CharField(choices=[('cash', 'نقدی'), ('agreement', 'توافقی')], default='cash', max_length=10, verbose_name='نوع عرضه پیشنهادی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تایید'), ('active', 'فعال'), ('sold', 'فروخته شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='draft', max_length=10, verbose_name='وضعیت عرضه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'عرضه کالا',
                'verbose_name_plural': 'عرضه\u200cهای کالا',
                'db_table': 'marketplace_product_offers',
                'ordering': ['-offer_date', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='marketplaceproduct',
            name='marketplace_marketp_dac94b_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketplaceproduct',
            name='marketplace_marketp_f43e24_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketplaceproduct',
            name='marketplace_is_acti_105acb_idx',
        ),
        migrations.AlterField(
            model_name='marketplaceproduct',
            name='internal_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='کالای داخلی مرتبط'),
        ),
        migrations.AlterField(
            model_name='marketplaceproductcategory',
            name='internal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.productcategory', verbose_name='گروه کالایی داخلی مرتبط'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='ضریب تبدیل'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='marketplace_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceproduct', verbose_name='کالای بازارگاه'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='warehouse_receipt',
            field=models.ForeignKey(limit_choices_to={'receipt_type__in': ['import_cottage', 'distribution_agency']}, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehousereceipt', verbose_name='رسید انبار (کوتاژ)'),
        ),
    ]
