# Generated by Django 5.2.4 on 2025-07-28 10:00

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_productoffer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cottage_number', models.CharField(editable=False, max_length=50, verbose_name='شماره کوتاژ')),
                ('product_title', models.CharField(editable=False, max_length=300, verbose_name='عنوان کالا')),
                ('offer_unit_price', models.DecimalField(decimal_places=0, editable=False, max_digits=15, verbose_name='فی عرضه')),
                ('total_offer_weight', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='وزن کل عرضه شده')),
                ('sold_weight_before_transport', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='وزن فروش رفته قبل از حمل')),
                ('remaining_weight_before_transport', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='وزن باقیمانده قبل از حمل')),
                ('sold_weight_after_transport', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='وزن فروش رفته پس از حمل')),
                ('remaining_weight_after_transport', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='وزن باقیمانده پس از حمل')),
                ('offer_status', models.CharField(editable=False, max_length=10, verbose_name='وضعیت عرضه')),
                ('entry_customs', models.CharField(blank=True, editable=False, max_length=200, verbose_name='گمرک ورودی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('product_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.productoffer', verbose_name='شناسه عرضه')),
            ],
            options={
                'verbose_name': 'فروش بازارگاه',
                'verbose_name_plural': 'فروش‌های بازارگاه',
                'db_table': 'marketplace_sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه خرید')),
                ('purchase_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن خرید')),
                ('purchase_date', django_jalali.db.models.jDateField(verbose_name='تاریخ خرید')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='نام خریدار')),
                ('buyer_mobile', models.CharField(max_length=15, verbose_name='شماره همراه خریدار')),
                ('buyer_national_id', models.CharField(max_length=10, verbose_name='شماره ملی خریدار')),
                ('paid_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ پرداختی')),
                ('purchase_type', models.CharField(choices=[('cash', 'نقدی'), ('agreement', 'توافقی')], max_length=20, verbose_name='نوع خرید')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('marketplace_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='marketplace.marketplacesale', verbose_name='فروش بازارگاه')),
            ],
            options={
                'verbose_name': 'خرید بازارگاه',
                'verbose_name_plural': 'خریدهای بازارگاه',
                'db_table': 'marketplace_purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_description', models.TextField(blank=True, verbose_name='توضیحات فروش توافقی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='marketplace.marketplacepurchase', verbose_name='خرید')),
            ],
            options={
                'verbose_name': 'جزئیات خرید بازارگاه',
                'verbose_name_plural': 'جزئیات خریدهای بازارگاه',
                'db_table': 'marketplace_purchase_details',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='کد')),
                ('total_purchase_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن کل خرید')),
                ('purchase_date', django_jalali.db.models.jDateField(verbose_name='تاریخ خرید')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر واحد')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهرستان')),
                ('paid_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ پرداختی')),
                ('buyer_account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب خریدار')),
                ('cottage_code', models.CharField(max_length=50, verbose_name='کد کوتاژ')),
                ('product_title', models.CharField(max_length=300, verbose_name='عنوان کالا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('payment_method', models.CharField(max_length=50, verbose_name='شیوه پرداخت')),
                ('offer_id', models.CharField(max_length=100, verbose_name='شناسه عرضه')),
                ('address_registration_date', django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت آدرس')),
                ('assignment_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه تخصیص')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='نام خریدار')),
                ('buyer_national_id', models.CharField(max_length=10, verbose_name='شناسه ملی خریدار')),
                ('buyer_postal_code', models.CharField(max_length=10, verbose_name='کدپستی خریدار')),
                ('buyer_address', models.TextField(verbose_name='آدرس خریدار')),
                ('deposit_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه واریز')),
                ('buyer_mobile', models.CharField(max_length=15, verbose_name='شماره همراه خریدار')),
                ('buyer_unique_id', models.CharField(max_length=100, verbose_name='شناسه یکتا خریدار')),
                ('buyer_user_type', models.CharField(choices=[('individual', 'حقیقی'), ('company', 'حقوقی')], max_length=20, verbose_name='نوع کاربری خریدار')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='نام تحویل گیرنده')),
                ('recipient_unique_id', models.CharField(max_length=100, verbose_name='شناسه یکتای تحویل')),
                ('vehicle_single', models.BooleanField(default=False, verbose_name='تک')),
                ('vehicle_double', models.BooleanField(default=False, verbose_name='جفت')),
                ('vehicle_trailer', models.BooleanField(default=False, verbose_name='تریلی')),
                ('delivery_address', models.TextField(verbose_name='آدرس تحویل')),
                ('delivery_postal_code', models.CharField(max_length=10, verbose_name='کد پستی تحویل')),
                ('coordination_phone', models.CharField(max_length=15, verbose_name='شماره هماهنگی تحویل')),
                ('delivery_national_id', models.CharField(max_length=10, verbose_name='کد ملی تحویل')),
                ('order_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن سفارش')),
                ('payment_period_1_days', models.IntegerField(blank=True, null=True, verbose_name='بازه 1 پرداخت توافقی (روز)')),
                ('payment_period_2_days', models.IntegerField(blank=True, null=True, verbose_name='بازه 2 پرداخت توافقی (روز)')),
                ('payment_period_3_days', models.IntegerField(blank=True, null=True, verbose_name='بازه 3 پرداخت توافقی (روز)')),
                ('payment_amount_1', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ بازه 1 توافقی-ریال')),
                ('payment_amount_2', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ بازه 2 توافقی-ریال')),
                ('payment_amount_3', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ بازه 3 توافقی-ریال')),
                ('shipped_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='وزن بارنامه شده')),
                ('unshipped_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='وزن بارنامه نشده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('purchase_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='marketplace.marketplacepurchasedetail', verbose_name='جزئیات خرید')),
            ],
            options={
                'verbose_name': 'آدرس تحویل',
                'verbose_name_plural': 'آدرس‌های تحویل',
                'db_table': 'marketplace_delivery_addresses',
                'ordering': ['-address_registration_date', '-created_at'],
            },
        ),
        
        # اضافه کردن indexes برای بهبود کارایی
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_marketplace_sale_cottage ON marketplace_sales(cottage_number);",
            reverse_sql="DROP INDEX IF EXISTS idx_marketplace_sale_cottage;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_marketplace_purchase_buyer ON marketplace_purchases(buyer_national_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_marketplace_purchase_buyer;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_delivery_address_assignment ON marketplace_delivery_addresses(assignment_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_delivery_address_assignment;"
        ),
    ]