# Generated by Django migration for fixing field lengths

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_add_indexes'),
    ]

    operations = [
        # افزایش طول فیلدهای کد ملی و کد پستی در DeliveryAddress
        migrations.AlterField(
            model_name='deliveryaddress',
            name='buyer_national_id',
            field=models.CharField(max_length=20, verbose_name='شناسه ملی خریدار'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='buyer_postal_code',
            field=models.CharField(max_length=20, verbose_name='کدپستی خریدار'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='delivery_postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی تحویل'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='delivery_national_id',
            field=models.CharField(max_length=20, verbose_name='کد ملی تحویل'),
        ),
        
        # افزایش طول فیلدهای کد ملی در MarketplacePurchase
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='buyer_national_id',
            field=models.CharField(max_length=20, verbose_name='شماره ملی خریدار'),
        ),
        
        # افزایش طول فیلدهای شماره تلفن در صورت نیاز
        migrations.AlterField(
            model_name='deliveryaddress',
            name='buyer_mobile',
            field=models.CharField(max_length=20, verbose_name='شماره همراه خریدار'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='coordination_phone',
            field=models.CharField(max_length=20, verbose_name='شماره هماهنگی تحویل'),
        ),
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='buyer_mobile',
            field=models.CharField(max_length=20, verbose_name='شماره همراه خریدار'),
        ),
        
        # اضافه کردن blank=True برای فیلدهای اختیاری
        migrations.AlterField(
            model_name='deliveryaddress',
            name='buyer_national_id',
            field=models.CharField(max_length=20, blank=True, verbose_name='شناسه ملی خریدار'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='buyer_postal_code',
            field=models.CharField(max_length=20, blank=True, verbose_name='کدپستی خریدار'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='delivery_postal_code',
            field=models.CharField(max_length=20, blank=True, verbose_name='کد پستی تحویل'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='delivery_national_id',
            field=models.CharField(max_length=20, blank=True, verbose_name='کد ملی تحویل'),
        ),
    ]