# Generated by Django 5.2.4 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_fix_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='purchase_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='شناسه خرید'),
        ),
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='purchase_type',
            field=models.CharField(choices=[('cash', 'نقدی'), ('agreement', 'توافقی'), ('mixed', 'ترکیبی')], max_length=20, verbose_name='نوع خرید'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['assignment_id'], name='idx_assignment_id'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['recipient_unique_id'], name='idx_recipient_unique'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['buyer_national_id'], name='idx_buyer_national'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['province', 'city'], name='idx_location'),
        ),
        migrations.AddIndex(
            model_name='marketplacepurchase',
            index=models.Index(fields=['purchase_id'], name='idx_purchase_id'),
        ),
        migrations.AddIndex(
            model_name='marketplacepurchase',
            index=models.Index(fields=['buyer_national_id'], name='idx_buyer_national_purchase'),
        ),
        migrations.AddIndex(
            model_name='marketplacepurchase',
            index=models.Index(fields=['purchase_date', 'purchase_type'], name='idx_purchase_date_type'),
        ),
    ]
