# Generated by Django 5.2.4 on 2025-07-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_marketplacepurchase_purchase_id_and_more'),
    ]

    operations = [
    ]
