# Generated by Django 5.2.4 on 2025-07-30 08:27

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20250730_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepurchase',
            name='agreement_amount_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ بازه 1 توافقی-ریال'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='agreement_amount_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ بازه 2 توافقی-ریال'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='agreement_amount_3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ بازه 3 توافقی-ریال'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='agreement_period_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='بازه 1 پرداخت توافقی (روز)'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='agreement_period_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='بازه 2 پرداخت توافقی (روز)'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='agreement_period_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='بازه 3 پرداخت توافقی (روز)'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='buyer_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره حساب خریدار'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='cottage_number',
            field=models.CharField(default='', help_text='باید با شماره کوتاژ عرضه تطابق داشته باشد', max_length=50, verbose_name='شماره کوتاژ'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='delivery_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='document_registration_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ثبت سند'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='product_title',
            field=models.CharField(default='', max_length=300, verbose_name='عنوان کالا'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='supply_id',
            field=models.CharField(default='', max_length=100, verbose_name='شناسه عرضه'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری'),
        ),
        migrations.AddField(
            model_name='marketplacepurchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت هر واحد-ریال'),
        ),
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='buyer_national_id',
            field=models.CharField(help_text='کد ملی یا شناسه ملی', max_length=20, verbose_name='کد ملی خریدار'),
        ),
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ پرداختی-ریال'),
        ),
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='purchase_type',
            field=models.CharField(choices=[('cash', 'نقدی'), ('agreement', 'توافقی'), ('mixed', 'ترکیبی')], max_length=20, verbose_name='شیوه پرداخت'),
        ),
        migrations.AlterField(
            model_name='marketplacepurchase',
            name='purchase_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن خرید شده-Kg'),
        ),
    ]
