# Generated by Django 5.2.4 on 2025-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_marketplacepurchase_agreement_amount_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='delivery_order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حواله خروج'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('sent_to_delivery', 'ارسال شده برای حواله'), ('delivery_created', 'حواله ایجاد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
