# Generated by Django 4.2.23 on 2025-08-01 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_add_receiver_system_id'),
        ('marketplace', '0010_remove_marketplace_products_use_warehouse_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='کالا'),
        ),
        migrations.CreateModel(
            name='DistributionAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('agency_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن عاملیت داده شده (کیلوگرم)')),
                ('cottage_number', models.CharField(editable=False, max_length=50, verbose_name='شماره کوتاژ')),
                ('agency_date', django_jalali.db.models.jDateField(verbose_name='تاریخ اعطای عاملیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.customer', verbose_name='مشتری (عامل توزیع)')),
                ('product_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='نوع کالا')),
                ('sales_proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.salesproforma', verbose_name='پیش\u200cفاکتور فروش')),
                ('warehouse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='انبار')),
                ('warehouse_receipt', models.ForeignKey(help_text='فقط رسیدهای کوتاژ وارداتی قابل انتخاب هستند', limit_choices_to={'receipt_type': 'import_cottage'}, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehousereceipt', verbose_name='رسید انبار')),
            ],
            options={
                'verbose_name': 'اعطای عاملیت توزیع',
                'verbose_name_plural': 'اعطای عاملیت\u200cهای توزیع',
                'db_table': 'distribution_agencies',
                'ordering': ['-agency_date', '-created_at'],
            },
        ),
    ]
