# Generated by Django 4.2.23 on 2025-08-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_productoffer_product_distributionagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='offer_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن عرضه (کیلوگرم)'),
        ),
    ]
