# Generated by Django 5.2.4 on 2025-08-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductReigon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Corporate", "Corporate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("national_id", models.CharField(blank=True, max_length=11)),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("personal_code", models.CharField(blank=True, max_length=10)),
                ("economic_code", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "baseparty_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.baseparty",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Corporate", "Corporate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("national_id", models.CharField(blank=True, max_length=11)),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("personal_code", models.CharField(blank=True, max_length=10)),
                ("economic_code", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            bases=("core.baseparty",),
        ),
        migrations.CreateModel(
            name="Reciever",
            fields=[
                (
                    "baseparty_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.baseparty",
                    ),
                ),
                (
                    "reciever_type",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Corporate", "Corporate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("system_id", models.CharField(max_length=50, unique=True)),
                ("unique_id", models.CharField(max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("national_id", models.CharField(blank=True, max_length=11)),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("personal_code", models.CharField(blank=True, max_length=10)),
                ("economic_code", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("postal_code", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            bases=("core.baseparty",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("b2bcode", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productcategory",
                    ),
                ),
                (
                    "b2breigon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productreigon",
                    ),
                ),
            ],
        ),
    ]
