# Generated by Django 5.2.4 on 2025-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "individual"),
                            ("corporate", "corporate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "national_id",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("full_name", models.CharField(blank=True, max_length=100)),
                (
                    "personal_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("economic_code", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("b2bcode", models.CharField(max_length=10, unique=True)),
                ("b2bregion", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_type",
                    models.CharField(
                        choices=[
                            ("individual", "individual"),
                            ("corporate", "corporate"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "receiver_veichle_type",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("double", "double"),
                            ("trailer", "trailer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unique_id", models.CharField(max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "national_id",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("full_name", models.CharField(blank=True, max_length=100)),
                (
                    "personal_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("economic_code", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("postal_code", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("individual", "individual"),
                            ("corporate", "corporate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "national_id",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("full_name", models.CharField(blank=True, max_length=100)),
                (
                    "personal_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("economic_code", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
