# Generated by Django 5.0.6 on 2025-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique indicator prefix used to build generated IDs.', max_length=100, unique=True)),
                ('counter', models.PositiveIntegerField(default=0, help_text='Number of identifiers created with this indicator.')),
                ('belongs', models.CharField(help_text='Name of the entity (e.g. sales proforma) this indicator belongs to.', max_length=100)),
            ],
        ),
    ]
