# Generated by Django 5.0.6 on 2025-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="b2bcode",
            field=models.CharField(max_length=10),
        ),
    ]
