# Generated by Django 5.0.6 on 2025-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="economic_code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="national_id",
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="personal_code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reciever",
            name="economic_code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="reciever",
            name="national_id",
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="reciever",
            name="personal_code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="economic_code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="national_id",
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="personal_code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
