# Generated by Django 5.0.6 on 2025-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Automatically selected indicator for its section.'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='belongs',
            field=models.CharField(help_text='Machine key describing the entity (e.g. sale_proforma) this indicator belongs to.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('belongs',), name='unique_default_indicator_per_section'),
        ),
    ]
