# Generated by Django 5.2.4 on 2025-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_receiver_system_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="personal_code",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="national_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="personal_code",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="personal_code",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
