# Generated by Django 5.0.6 on 2025-08-10 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_customer_economic_code_and_more"),
        (
            "warehouse",
            "0003_rename_shippment_price_deliveryfulfillmentitem_shipment_price",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductReigon",
            new_name="ProductRegion",
        ),
        migrations.RenameModel(
            old_name="Reciever",
            new_name="Receiver",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="b2breigon",
            new_name="b2bregion",
        ),
        migrations.RenameField(
            model_name="receiver",
            old_name="reciever_type",
            new_name="receiver_type",
        ),
    ]
