# Generated by Django 5.0.6 on 2025-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_b2bcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiver",
            name="receiver_veichle_type",
        ),
        migrations.RemoveField(
            model_name="receiver",
            name="unique_id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
    ]
