# Generated by Django 5.0.6 on 2025-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_productreigon_productregion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="national_id",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="personal_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="national_id",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="personal_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="national_id",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="personal_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
