# Generated by Django 5.2.4 on 2025-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_customer_personal_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiver",
            name="national_id",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
