# Generated by Django 5.0.6 on 2025-11-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_indicator_is_default_alter_indicator_belongs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='format_template',
            field=models.TextField(default='{{COUNTER3}}', help_text='Template used to build identifiers. Supports literal text plus tokens such as {{JYEAR4}} or {{COUNTER4}}.'),
        ),
    ]
