# Generated by Django 5.0.6 on 2025-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_indicator_format_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='end_number',
            field=models.PositiveIntegerField(default=999, help_text='Ending number for the counter range. Used to auto-calculate digit count.'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='start_number',
            field=models.PositiveIntegerField(default=1, help_text='Starting number for the counter range.'),
        ),
    ]
