# Generated by Django 5.0.6 on 2025-08-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_customer_economic_code_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proformaline",
            old_name="profoma",
            new_name="proforma",
        ),
        migrations.AlterField(
            model_name="salesproforma",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.customer"
            ),
        ),
    ]
