# Generated by Django 5.0.6 on 2025-08-11 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_rename_profoma_proformaline_proforma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proforma",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proforma",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
