# Generated by Django 5.0.6 on 2026-02-22 11:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_salesproformaexportpreset_salesproforma_commission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesProformaExportPreset',
            new_name='ProformaExportPreset',
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='export_preset',
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='other_cost',
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='proforma',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proforma',
            name='export_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='finance.proformaexportpreset'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='other_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proforma',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
