# Generated by Django 5.0.6 on 2025-12-13 05:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_salesproformaexportpreset_salesproforma_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='salesproforma',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='salesproforma',
            name='other_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='salesproforma',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
