# Generated by Django 5.0.6 on 2026-01-25 12:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_proforma_discount_alter_proforma_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaExportPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=64)),
                ('sheba_number', models.CharField(max_length=34)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='export_preset',
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='other_cost',
        ),
        migrations.RemoveField(
            model_name='salesproforma',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='proforma',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proforma',
            name='other_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proforma',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='proforma',
            name='export_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='finance.proformaexportpreset'),
        ),
        migrations.DeleteModel(
            name='SalesProformaExportPreset',
        ),
    ]
