# Generated by Django 5.2.4 on 2025-08-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_id", models.CharField(max_length=100, unique=True)),
                (
                    "cottage_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "purchase_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("province", models.CharField(default="", max_length=100)),
                ("purchase_date", models.DateField()),
                ("paid_amount", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("document_registration_date", models.DateField(blank=True, null=True)),
                ("product_title", models.CharField(default="", max_length=300)),
                ("buyer_national_id", models.CharField(max_length=20)),
                ("buyer_account_number", models.CharField(blank=True, max_length=50)),
                ("buyer_mobile", models.CharField(max_length=20)),
                ("buyer_name", models.CharField(max_length=200)),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("agreement", "agreement"),
                            ("mixed", "mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "agreement_period_1",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "agreement_period_2",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "agreement_period_3",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "agreement_amount_1",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                (
                    "agreement_amount_2",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                (
                    "agreement_amount_3",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                ("supply_id", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="B2BOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_id", models.CharField(max_length=100, unique=True)),
                (
                    "cottage_number",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                ("offer_date", models.DateTimeField()),
                ("offer_exp_date", models.DateTimeField()),
                ("offer_weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=16)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=6, editable=False, max_digits=16
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("credit", "credit"),
                            ("agreement", "agreement"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "warehouse_receipt",
                    models.ForeignKey(
                        limit_choices_to={
                            "receipt_type__in": [
                                "import_cottage",
                                "distribution_agency",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehousereceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "cottage_number",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                ("agency_date", models.DateTimeField()),
                (
                    "agency_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "warehouse_receipt",
                    models.ForeignKey(
                        limit_choices_to={"receipt_type": "import_cottage"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehousereceipt",
                    ),
                ),
                (
                    "b2b_offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributions",
                        to="b2b.b2boffer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BPurchaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_description", models.TextField(blank=True)),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="b2b.b2bpurchase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cottage_number",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                (
                    "product_title",
                    models.CharField(default="", editable=False, max_length=300),
                ),
                (
                    "offer_unit_price",
                    models.DecimalField(
                        decimal_places=6, editable=False, max_digits=16
                    ),
                ),
                (
                    "total_offer_weight",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "sold_weight_before_transport",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "remaining_weight_before_transport",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "sold_weight_after_transport",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "remaining_weight_after_transport",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "offer_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                        ],
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "entry_customs",
                    models.CharField(blank=True, editable=False, max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale",
                        to="b2b.b2boffer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="b2bpurchase",
            name="b2b_sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="b2b.b2bsale",
            ),
        ),
    ]
