# Generated by Django 5.2.4 on 2025-08-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
        ("warehouse", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_id", models.CharField(max_length=100, unique=True)),
                ("cottage_number", models.CharField(blank=True, max_length=50)),
                ("offer_date", models.DateTimeField()),
                ("offer_exp_date", models.DateTimeField()),
                ("offer_weight", models.DecimalField(decimal_places=4, max_digits=20)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("total_price", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("credit", "credit"),
                            ("agreement", "agreement"),
                            ("other", "other"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("active", "active"),
                            ("sold", "sold"),
                            ("expired", "expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "warehouse_receipt",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "receipt_type__in": [
                                "import_cottage",
                                "distribution_cottage",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.warehousereceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("agency_date", models.DateTimeField()),
                (
                    "agency_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "b2b_offer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="b2b.b2boffer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_id",
                    models.CharField(default="", max_length=100, unique=True),
                ),
                (
                    "allocation_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("cottage_code", models.CharField(blank=True, max_length=50)),
                (
                    "total_weight_purchased",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("purchase_date", models.DateField(null=True)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("credit_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.receiver",
                    ),
                ),
                (
                    "product_offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="b2b.b2boffer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_id", models.CharField(max_length=100, unique=True)),
                ("cottage_code", models.CharField(blank=True, max_length=50)),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("sale_date", models.DateField(null=True)),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("credit", "credit"),
                            ("agreement", "agreement"),
                            ("other", "other"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_sales",
                        to="b2b.b2boffer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
    ]
