# Generated by Django 5.2.4 on 2025-08-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("finance", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2bDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agency_date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "agency_weight",
                    models.DecimalField(decimal_places=8, default=0, max_digits=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "sales_proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.salesproforma",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "warehouse_receipt",
                    models.ForeignKey(
                        limit_choices_to={"receipt_type": "import_cottage"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehousereceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_id", models.CharField(max_length=100, unique=True)),
                ("offer_date", models.DateTimeField()),
                ("offer_exp_date", models.DateTimeField()),
                (
                    "offer_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="وزن عرضه (کیلوگرم)",
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=16)),
                ("total_price", models.DecimalField(decimal_places=6, max_digits=16)),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("credit", "credit"),
                            ("agreement", "agreement"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("pending", "pending"),
                            ("active", "active"),
                            ("sold", "sold"),
                            ("expired", "expired"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "warehouse_receipt",
                    models.ForeignKey(
                        limit_choices_to={
                            "receipt_type__in": [
                                "import_cottage",
                                "distribution_agency",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehousereceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_unit_price",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "total_offer_weight",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "sold_weight_before_transport",
                    models.DecimalField(decimal_places=8, default=0, max_digits=16),
                ),
                (
                    "remaining_weight_before_transport",
                    models.DecimalField(decimal_places=8, default=0, max_digits=16),
                ),
                (
                    "sold_weight_after_transport",
                    models.DecimalField(decimal_places=8, default=0, max_digits=16),
                ),
                (
                    "remaining_weight_after_transport",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "offer_status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("pending", "pending"),
                            ("active", "active"),
                            ("sold", "sold"),
                            ("expired", "expired"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("entry_customs", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="b2b.b2boffer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BSaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.customer"
                    ),
                ),
                (
                    "marketplace_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="b2b.b2bsale",
                    ),
                ),
            ],
        ),
    ]
