# Generated by Django 5.0.6 on 2025-09-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2baddress",
            name="address_register_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="customer_account_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="deposit_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="double",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="non_waybilled_weight",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="purchase_weight",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="single",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="trailer",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="waybilled_weight",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
