# Generated by Django 5.0.6 on 2025-08-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
        ("core", "0004_alter_receiver_national_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="b2bsale",
            name="cottage_number",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="entry_customs",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="offer_status",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="offer_unit_price",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="product_title",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="remaining_weight_after_transport",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="remaining_weight_before_transport",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="sold_weight_after_transport",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="sold_weight_before_transport",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="total_offer_weight",
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="allocation_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="cottage_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="credit_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="payment_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="purchase_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="purchase_id",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.receiver",
            ),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="total_weight_purchased",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="unit_price",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="product_offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="b2b.b2boffer",
            ),
        ),
    ]
