# Generated by Django 5.0.6 on 2025-08-11 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
        ("core", "0003_rename_productreigon_productregion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2bdistribution",
            name="cottage_number",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="b2boffer",
            name="cottage_number",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="cottage_number",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="product_title",
            field=models.CharField(default="", editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name="b2bdistribution",
            name="agency_weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="b2boffer",
            name="offer_weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="b2boffer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.product"
            ),
        ),
        migrations.AlterField(
            model_name="b2boffer",
            name="total_price",
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="entry_customs",
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="offer_status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("pending", "pending"),
                    ("active", "active"),
                    ("sold", "sold"),
                    ("expired", "expired"),
                    ("cancelled", "cancelled"),
                ],
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="offer_unit_price",
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="product_offer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale",
                to="b2b.b2boffer",
            ),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="remaining_weight_after_transport",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="remaining_weight_before_transport",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="sold_weight_after_transport",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="sold_weight_before_transport",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="total_offer_weight",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name="B2BPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_id", models.CharField(max_length=100, unique=True)),
                (
                    "cottage_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "purchase_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("province", models.CharField(default="", max_length=100)),
                ("purchase_date", models.DateField()),
                ("paid_amount", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("document_registration_date", models.DateField(blank=True, null=True)),
                ("product_title", models.CharField(default="", max_length=300)),
                ("buyer_national_id", models.CharField(max_length=20)),
                ("buyer_account_number", models.CharField(blank=True, max_length=50)),
                ("buyer_mobile", models.CharField(max_length=20)),
                ("buyer_name", models.CharField(max_length=200)),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("agreement", "agreement"),
                            ("mixed", "mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "agreement_period_1",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "agreement_period_2",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "agreement_period_3",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "agreement_amount_1",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                (
                    "agreement_amount_2",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                (
                    "agreement_amount_3",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                ("supply_id", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "b2b_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="b2b.b2bsale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BPurchaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_description", models.TextField(blank=True)),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="b2b.b2bpurchase",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="B2BSaleDetail",
        ),
    ]
