# Generated by Django 5.0.6 on 2025-09-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="b2boffer",
            name="cottage_number",
        ),
        migrations.RemoveField(
            model_name="b2boffer",
            name="product",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="cottage_code",
        ),
        migrations.RemoveField(
            model_name="b2bsale",
            name="product",
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="b2b_distribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="b2b_sales",
                to="b2b.b2bdistribution",
            ),
        ),
        migrations.AddField(
            model_name="b2bsale",
            name="is_distributor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="b2baddress",
            name="payment_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2baddress",
            name="total_weight_purchased",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2baddress",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2bdistribution",
            name="agency_weight",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2boffer",
            name="offer_weight",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2boffer",
            name="total_price",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2boffer",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="total_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="b2bsale",
            name="weight",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
