# Generated by Django 5.0.6 on 2025-08-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0002_remove_b2bsale_cottage_number_and_more"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b2boffer",
            name="warehouse_receipt",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "receipt_type__in": ["import_cottage", "distribution_agency"]
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.warehousereceipt",
            ),
        ),
    ]
