# Generated by Django 5.0.6 on 2025-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0002_b2baddress_address_register_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2baddress",
            name="agreement_amount_1",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="agreement_amount_2",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="agreement_amount_3",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="agreement_period_1",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="agreement_period_2",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="agreement_period_3",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="b2baddress",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
