# Generated by Django 5.0.6 on 2025-08-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0003_make_warehouse_receipt_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="b2bdistribution",
            name="cottage_number",
        ),
        migrations.RemoveField(
            model_name="b2bdistribution",
            name="warehouse_receipt",
        ),
        migrations.AlterField(
            model_name="b2bdistribution",
            name="b2b_offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="b2b.b2boffer",
            ),
        ),
    ]
