# Generated by Django 5.0.6 on 2025-10-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_b2baddress_agreement_amount_1_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bdistribution',
            name='sales_proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.salesproforma'),
        ),
        migrations.AddField(
            model_name='b2bdistribution',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
