# Generated by Django 5.0.6 on 2025-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_b2bdistribution_sales_proforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bsale',
            name='cottage_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
