# Generated by Django 5.0.6 on 2025-10-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0005_alter_b2bsale_cottage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bsale',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_sales', to='b2b.b2boffer'),
        ),
    ]
