# Generated by Django 5.0.6 on 2025-10-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0006_alter_b2bsale_offer'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bsale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
