# Generated by Django 5.0.6 on 2025-10-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0007_b2bsale_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2bsale',
            name='cottage_code',
        ),
        migrations.RemoveField(
            model_name='b2bsale',
            name='product',
        ),
        migrations.AlterField(
            model_name='b2bsale',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_sales', to='b2b.b2boffer'),
        ),
    ]
