# Generated by Django 5.0.6 on 2025-10-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_b2bsale_product'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bsale',
            name='sales_proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_sales', to='finance.salesproforma'),
        ),
        migrations.AlterField(
            model_name='b2bsale',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_sales', to='b2b.b2boffer'),
        ),
    ]
