# Generated by Django 5.0.6 on 2025-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_link_existing_sales_to_proformas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2baddress',
            name='allocation_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='b2baddress',
            name='purchase_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
