# Generated by Django 5.0.6 on 2025-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0012_alter_b2baddress_allocation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2baddress',
            name='allocation_id',
            field=models.CharField(default='', error_messages={'unique': 'آدرس بازارگاه با این شماره تخصیص قبلاً ثبت شده است.'}, max_length=100, unique=True),
        ),
    ]
