# Generated by Django 5.0.6 on 2025-11-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0013_alter_b2baddress_allocation_id'),
        ('warehouse', '0009_alter_deliveryfulfillment_waybill_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2boffer',
            name='warehouse_receipt',
            field=models.ForeignKey(default=0, limit_choices_to={'receipt_type__in': ['import_cottage', 'distribution_cottage']}, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehousereceipt'),
            preserve_default=False,
        ),
    ]
